version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - app/.env
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - app/.env

  minio:
    image: minio/minio:latest
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    env_file:
      - app/.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./deploy/minio/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - reverse-proxy
    labels:
      - traefik.http.routers.minio.rule=Host(`minio.localhost`)
      - traefik.http.routers.minio-console.rule=Host(`minio-console.localhost`)

  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      #
      - /var/run/docker.sock:/var/run/docker.sock